---
- name: Deploy Telegraf to all nodes
  hosts: all
  become: true
  pre_tasks:
    - name: Parse .env file and set variables
      block:
        - name: Read .env file
          slurp:
            src: '{{ playbook_dir }}/.env'
          register: env_file
          delegate_to: localhost
          become: false
          run_once: true

        - name: Set InfluxDB variables from .env
          set_fact:
            influxdb_host: "{{ (env_file.content | b64decode | regex_search('INFLUXDB_HOST=(.+)$', '\\1', multiline=True) | first) }}"
            influxdb_port: "{{ (env_file.content | b64decode | regex_search('INFLUXDB_PORT=(.+)$', '\\1', multiline=True) | first) }}"
            influxdb_org: "{{ (env_file.content | b64decode | regex_search('INFLUXDB_ORG=(.+)$', '\\1', multiline=True) | first) }}"
            influxdb_bucket: "{{ (env_file.content | b64decode | regex_search('INFLUXDB_BUCKET=(.+)$', '\\1', multiline=True) | first) }}"
            influxdb_token: "{{ (env_file.content | b64decode | regex_search('INFLUXDB_TOKEN=(.+)$', '\\1', multiline=True) | first) }}"
          run_once: true
      become: false

  roles:
    - telegraf
